/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'peer' at '22.03.16 17:27' with Gradle 2.4
 *
 * @author peer, @date 22.03.16 17:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
